const ar = {
  // Header
  Home: "الرئيسية",
  Wishlist: "المفضلة",
  Cart: "عربة التسوق",
  Orders: "الطلبات",
  Search: "بحث",
  about: "من نحن",
  contact: "اتصل بنا",
  theme: "الموضوع الحالي هو",
  lang: "اللغة الحالية هي",
  themebtn: "تبديل الموضوع",
  langbtn: "تبديل اللغة",
  light: "فاتح",
  dark: "داكن",
  english: "الإنجليزية",
  arabic: "العربية",
  aboutus: "من نحن",

  // Auth
  Login: "تسجيل الدخول",
  Register: "تسجيل حساب جديد",
  title: "تسجيل الدخول إلى المتجر الذكي",
  subTitle: "من فضلك أدخل تفاصيلك!",
  Input1: "البريد الإلكتروني / اسم المستخدم",
  emailPlaceHolder: "أدخل بريدك الإلكتروني",
  emailRequired: "البريد الإلكتروني مطلوب.",
  invalidEmail: "تنسيق البريد الإلكتروني غير صحيح.",
  Input2: "كلمة المرور",
  passwordPlaceHolder: "أدخل كلمة المرور الخاصة بك",
  passErrLength: "يجب أن تكون كلمة المرور على الأقل 8 أحرف.",
  passwordForgot: "هل نسيت كلمة المرور؟",
  SignIn: "تسجيل الدخول",
    "Select your role": "اختر دورك",

  // Register
  regTitle: "إنشاء حساب",
  regSubTitle: "أدخل تفاصيلك أدناه لإنشاء حسابك في المتجر الذكي.",
  nameinput: "الاسم",
  namePlaceholder: "أدخل اسمك الكامل",
  inputemail: "البريد الإلكتروني",
  regEmailPlaceholder: "أدخل عنوان بريدك الإلكتروني",
  regpassword: "كلمة المرور",
  reqpassword: " كلمة المرور مطلوبة",
  reqname: "اسم المستخدم مطلوب",
  unmatch:"كلمة المرور غير متطابقة",
  roleRequired:"الدور مطلوب",
  regpasswordPlaceholder: "أنشئ كلمة مرور",
  confirmPassword: "تأكيد كلمة المرور",
  confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
  Role: "الدور",
  selectRole: "اختر دورك",
  Here: "(سجل هنا)",
  DontHaveAccount: "لا تمتلك حسابًا؟.",
  regUser: "مستخدم",
  regAdmin: "مدير",
  btnRegister: "تسجيل",
  accExists: "لديك حساب بالفعل ؟ ",
  passErrPattern: " كلمة المرور يجب ان يكون على الاقل 8 حروف و تحتوي على حرف كبير وحرف صغير ورقم ورمز خاص .",
  fromLastMonth: "من الشهر الماضي",
  // Wishlist Card
  addtocart: "اضافة الى السلة",
  remove: "حذف",
  // Wishlist
  wishlistTitle: "قائمة رغباتك",
  wishlistDescEmpty: "قائمة رغباتك فارغة. ابدأ بإضافة المنتجات التي تحبها!",
  wishlistDescNotEmpty: "هذه هي المنتجات التي حفظتها لاحقًا. هل أنت جاهز لامتلاكها؟",
  emptyWishlist: "لا توجد منتجات في قائمة رغباتك.",
  modalConfirmDeleteTitle: "تأكيد الحذف",
  modalConfirmDeleteMessage: "هل أنت متأكد أنك تريد إزالة هذا المنتج من قائمة رغباتك؟",
  cancel: "إلغاء",
  delete: "حذف",
  wishlistItemRemoved: "تمت إزالة المنتج من قائمة الرغبات.",
  // Cart Shopping
  cartTitle: "سلة التسوق الخاصة بك",
  cartDescEmpty: "سلة التسوق فارغة، ابدأ بإضافة المنتجات التي تحبها!",
  modalConfirmDeleteTitleCart: "تأكيد الحذف",
  modalConfirmDeleteMessageCart: "هل تريد حذف هذا المنتج من سلة التسوق الخاصة بك؟",
  returnShopping: "العوده للتسوق",
  // Order Summary
  orderSummaryTitle: "ملخص الطلب",
  orderSummaryDescription: "قم بمراجعة العناصر والتكلفة الكلية قبل تقديم الطلب.",
  summarySubtotal: "المجموع الفرعي",
  summaryShipping: "الشحن",
  summaryDiscount: "الخصم",
  summaryTotal: "المجموع الكلي",
  placeOrder: "تقديم الطلب",
  // Orders
  ordertitle: "طلباتك",
  dropdownallorders: "كل الطلبات",
  dropdownpendingorders: "قيد الانتظار",
  dropdowncompletedorders: "مكتملة",
  dropdowncancelledorders: "ملغية",
  //Footer
  siteName: "وودي",
  siteTagline: "لأثاث طبيعي",
  footerDescription: "الوصف",
  footerDescriptionText: "فريق صغير قام ببناء هذا الموقع لتجارة الأثاث العصري الصديق للبيئة والمستدام.",
  footerServices: "الخدمات",
  footerProducts: "التصنيفات",
  footerAbout: "من نحن",
  footerCustomer: "العملاء",
  footerServicesItems: ["شراء وبيع", "الحجز", "سياسة الإرجاع"],
  living: "غرفة المعيشه",
  office: "مكتب",
  dinning: "غرفة الطعام",
  Bedroom: "غرفة النوم",
  Kitchen: "مطبخ",
  staff: "طاقم العمل",
  ourWorks: "اعمالنا",
  careers: "الوظائف",
  reviews: "المراجعات والتقييمات",
  log: "تسجيل الدخول",
  reg: "التسجيل",
  contactUs: "اتصل بنا",
  help:"المساعدة والدعم",
  copyrightText: "© 2025 وودي. جميع الحقوق محفوظة.",
  // NotFound Page
  oops:"أوووه!",
  notfoundtitle: "صفحة غير موجودة",
  notfoundmessage1: "الصفحة التي تبحث عنها غير موجودة،",
  notfoundmessage2: "قد تكون تم نقلها او تم حذفها.",
  notfoundmessage3: "يرجى التحقق من الرابط او العودة إلى الصفحة الرئيسية.",
  // Dashboard Sidebar
  dashboardhome: "الإداره",
  manageproducts: "إداره المنتجات",
  managecategories: "إداره التصنيفات",
  manageorders: "إداره الطلبات",
  analytics: "التحليلات",
  settings: "الإعدادت",
  // Dashboard Home
  dashboardWelcome: "مرحباً بعودتك، أيها المدير!",
  dashboardOverview: "إليك نظرة سريعة على أداء منصتك للتجارة الإلكترونية.",
  totalProducts: "إجمالي المنتجات",
  totalOrders: "إجمالي الطلبات",
  totalSales: "إجمالي المبيعات",
  activeUsers: "المستخدمون النشطون",
};

export default ar;