const ar = {
  Home: "الرئيسية",
  Wishlist: "المفضلة",
  Cart: "عربة التسوق",
  Orders: "الطلبات",
  Search: "بحث",
  about: "من نحن",
  contact: "اتصل بنا",
  theme: "الموضوع الحالي هو",
  lang: "اللغة الحالية هي",
  themebtn: "تبديل الموضوع",
  langbtn: "تبديل اللغة",
  light: "فاتح",
  dark: "داكن",
  english: "الإنجليزية",
  arabic: "العربية",
  aboutus: "من نحن",

  // Auth
  Login: "تسجيل الدخول",
  Register: "تسجيل حساب جديد",
  title: "تسجيل الدخول إلى المتجر الذكي",
  subTitle: "من فضلك أدخل تفاصيلك!",
  Input1: "البريد الإلكتروني / اسم المستخدم",
  emailPlaceHolder: "أدخل بريدك الإلكتروني",
  emailRequired: "البريد الإلكتروني مطلوب.",
  Input2: "كلمة المرور",
  passwordPlaceHolder: "أدخل كلمة المرور الخاصة بك",
  passErrLength: "يجب أن تكون كلمة المرور على الأقل 6 أحرف.",
  passwordForgot: "هل نسيت كلمة المرور؟",
  SignIn: "تسجيل الدخول",
    "Select your role": "اختر دورك",

  // Register
  regTitle: "إنشاء حساب",
  regSubTitle: "أدخل تفاصيلك أدناه لإنشاء حسابك في المتجر الذكي.",
  nameinput: "الاسم",
  namePlaceholder: "أدخل اسمك الكامل",
  inputemail: "البريد الإلكتروني",
  regEmailPlaceholder: "أدخل عنوان بريدك الإلكتروني",
  regpassword: "كلمة المرور",
  regpasswordPlaceholder: "أنشئ كلمة مرور",
  confirmPassword: "تأكيد كلمة المرور",
  confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
  Role: "الدور",
  selectRole: "اختر دورك",
  Here: "(سجل هنا)",
  DontHaveAccount: "لا تمتلك حسابًا؟.",
  regUser: "مستخدم",
  regAdmin: "مدير",
  btnRegister: "تسجيل",
  accExists: "حساب موجود بالفعل، يرجى تسجيل الدخول.",

  // WishList
  wishlistTitle: (count) => `قائمة رغباتك (${count} منتج)`,
  wishlistDesc: (count) =>
      count > 0
        ? "هذه هي المنتجات التي حفظتها لاحقًا. هل أنت جاهز لامتلاكها؟"
        : "قائمة رغباتك فارغة. ابدأ بإضافة المنتجات التي تحبها!",
  emptyWishlist: "لا توجد منتجات في قائمة رغباتك.",
  modalConfirmDeleteTitle: "تأكيد الحذف",
  modalConfirmDeleteMessage: (item) => `هل أنت متأكد أنك تريد إزالة "${item}" من قائمة رغباتك؟`,
  cancel: "إلغاء",
  delete: "حذف",
  wishlistItemRemoved: "تمت إزالة المنتج من قائمة الرغبات.",
  //Footer
  siteName: "وودي",
  siteTagline: "لأثاث طبيعي",
  footerDescription: "الوصف",
  footerDescriptionText: "فريق صغير قام ببناء هذا الموقع لتجارة الأثاث العصري الصديق للبيئة والمستدام.",
  footerServices: "الخدمات",
  footerProducts: "المنتجات",
  footerAbout: "من نحن",
  footerCustomer: "العملاء",
  footerServicesItems: ["شراء وبيع", "الحجز", "سياسة الإرجاع"],
  copyrightText: "© 2025 وودي. جميع الحقوق محفوظة.",

// Dashboard Home
  dashboardWelcome: "مرحباً بعودتك، أيها المدير!",
  dashboardOverview: "إليك نظرة سريعة على أداء منصتك للتجارة الإلكترونية.",
  totalProducts: "إجمالي المنتجات",
  totalOrders: "إجمالي الطلبات",
  totalSales: "إجمالي المبيعات",
  activeUsers: "المستخدمون النشطون",
  fromLastMonth: "من الشهر الماضي",
};

export default ar;
