const en = {
  // Header
  Home: "Home",
  Wishlist: "Wishlist",
  Cart: "Cart",
  Orders: "Orders",
  Search: "Search",
  about: "About",
  contact: "Contact",
  theme: "Current Theme is",
  lang: "Current Language is",
  themebtn: "Toggle Theme",
  langbtn: "Toggle Language",
  light: "Light",
  dark: "Dark",
  english: "English",
  arabic: "Arabic",
  aboutus: "About Us",
  // Auth
  Login: "Login",
  Register: "Register",
  title: "Login to ShopSmart",
  subTitle: "Please enter your details back!",
  Input1: "Email / Username",
  emailPlaceHolder: "Enter your email",
  emailRequired: "Email is required.",
  invalidEmail: "Invalid email format.",
  Input2: "Password",
  passwordPlaceHolder: "Enter your password",
  passErrLength: "Password must be at least 8 characters.",
  passwordForgot: "Forgot Password?",
  DontHaveAccount: "Don't have an account?",
  btnRegister: "Register",
  SignIn: "Sign In",
  // Register
  regTitle: "Create Account",
  regSubTitle: "Enter your details below to create your ShopSmart account.",
  nameinput: "Name",
  namePlaceholder: "Enter your full name",
  inputemail: "Email",
  regEmailPlaceholder: "Enter your email address",
  regpassword: "Password",
  reqpassword: "password is required",
  reqname: "name is required",
  unmatch: "passwords do not match",
  roleRequired: "role is required",
  regpasswordPlaceholder: "Create a password",
  confirmPassword: "Confirm Password",
  confirmPasswordPlaceholder: "Re-enter your password",
  Role: "Role",
  selectRole: "Select your role",
  Here: "Login here.",
  regUser: "User",
  regAdmin: "Admin",
  accExists: "Already have an account?",
  passErrPattern: "Password must be at least 8 characters and contain at least one uppercase letter, one lowercase letter, and one number.",
  // Wishlist Card
  addtocart: "Add to Cart",
  remove: "Remove",
  // Wishlist
  wishlistTitle: "Your Wishlist", 
  wishlistDescEmpty: "Your wishlist is empty. Start adding products you love!",
  wishlistDescNotEmpty: "Here are the products you've saved for later. Ready to make them yours?",
  emptyWishlist: "No items found in your Wishlist.",
  modalConfirmDeleteTitle: "Confirm Delete",
  modalConfirmDeleteMessage: "Are you sure you want to remove this item from your wishlist?",
  cancel: "Cancel",
  delete: "Delete",
  wishlistItemRemoved: "Item removed from wishlist.",
  // Cart Shopping
  cartTitle: "Your Shopping Cart",
  cartDescEmpty: "Your cart is empty, Start adding products you love!",
  modalConfirmDeleteTitleCart: "Confirm Delete",
  modalConfirmDeleteMessageCart: "Are you sure you want to remove this item from your cart?",
  returnShopping: "Return to Shop",
  // Order Summary
  orderSummaryTitle: "Order Summary",
  orderSummaryDescription: "Review your items and total cost before placing the order.",
  summarySubtotal: "Subtotal",
  summaryShipping: "Shipping",
  summaryDiscount: "Discount",
  summaryTotal: "Total",
  placeOrder: "Place Order",
  // Orders
  ordertitle: "Your Orders",
  dropdownallorders: "All Orders",
  dropdownpendingorders: "Pending",
  dropdowncompletedorders: "Completed",
  dropdowncancelledorders: "Cancelled",
  //Footer
  siteName: "WOODY",
  siteTagline: "For Natural Furniture",
  footerDescription: "Description",
  footerDescriptionText: "A small team built this site for trading modern furniture which is environmentally friendly and sustainable.",
  footerServices: "Services",
  footerProducts: "Categories",
  footerAbout: "About",
  footerCustomer: "Customer",
  footerServicesItems: ["Buy & Sell", "Reservation", "Return Policy"],
  living: "Living Room",
  office: "Office",
  dinning: "Dining",
  Bedroom: "Bedroom",
  Kitchen: "Kitchen",
  staff: "Staff",
  ourWorks: "Our Works",
  careers: "Careers",
  reviews: "Reviews",
  log: "Log in",
  reg: "Register",
  contactUs: "Contact Us",
  help:"Help & Support",
  copyrightText: "© 2025 WOODY. All rights reserved.",
  //NotFound Page
  oops: "Oops!",
  notfoundtitle: "Page Not Found",
  notfoundmessage1: "The page you're looking for doesn't exist,",
  notfoundmessage2: "It might have been moved or deleted.",
  notfoundmessage3: "please check the URL or go back to the homepage.",
  // Dashboard Sidebar
  dashboardhome: "Dashboard",
  manageproducts: "Manage Products",
  managecategories: "Manage Categories",
  manageorders: "Manage Orders",
  analytics: "Analytics",
  settings: "Settings",
  //Dashboard Home
  dashboardWelcome: "Welcome Back, Admin!",
  dashboardOverview: "Here's a quick overview of your e-commerce platform's performance.",
  totalProducts: "Total Products",
  totalOrders: "Total Orders",
  totalSales: "Total Sales",
  activeUsers: "Active Users",
  fromLastMonth: "from last month"
};

export default en;