const en = {
  Home: "Home",
  Wishlist: "Wishlist",
  Cart: "Cart",
  Orders: "Orders",
  Search: "Search",
  about: "About",
  contact: "Contact",
  theme: "Current Theme is",
  lang: "Current Language is",
  themebtn: "Toggle Theme",
  langbtn: "Toggle Language",
  light: "Light",
  dark: "Dark",
  english: "English",
  arabic: "Arabic",
  aboutus: "About Us",

  // Auth
  Login: "Login",
  Register: "Register",
  "Login to ShopSmart": "Login to ShopSmart",
  "Please enter your details back!": "Please enter your details back!",
  "Email / Username": "Email / Username",
  "Enter your email": "Enter your email",
  "Email is required.": "Email is required.",
  Password: "Password",
  "Enter your password": "Enter your password",
  "Password must be at least 6 characters.": "Password must be at least 6 characters.",
  "Forgot Password?": "Forgot Password?",
  "Sign In": "Sign In",

  // Register
  "Create Account": "Create Account",
  "Enter your details below to create your ShopSmart account.": "Enter your details below to create your ShopSmart account.",
  Name: "Name",
  "Enter your full name": "Enter your full name",
  Email: "Email",
  "Enter your email address": "Enter your email address",
  "Create a password": "Create a password",
  "Confirm Password": "Confirm Password",
  "Re-enter your password": "Re-enter your password",
  Role: "Role",
  "Select your role": "Select your role",
  AccountExists: "Already have an account?",
Here: "Login here.",
 DontHaveAccount: "Don't have an account?",
 "user": "User",
 "admin": "Admin",
};

export default en;
